# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eric Dean Barry
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a little blog about me and my interests. Hotrods, LDS beliefs, Liberty, Linux
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ericdeanbarry.com" # the base hostname & protocol for your site

# Pagination
paginate: 3
paginate_path: "/page:num/"

# Social and Site links

twitter_username:     EricDBarry
github_username:      EricDeanBarry
linkedin_username:    eric-barry-04432210
google_plus_username: u/0/104242951815697774681/posts
facebook_username:    EricDBarry

# Build settings
markdown: kramdown
exclude: ["README.md", "CNAME"]
gems: [jekyll-paginate]
